# -*- coding: utf-8 -*-
"""huggingface_text_finetune_qlora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/google-gemma/cookbook/blob/main/docs/core/huggingface_text_finetune_qlora.ipynb

##### Copyright 2025 Google LLC.
"""

#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""# Fine-Tune Gemma using Hugging Face Transformers and QloRA

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://ai.google.dev/gemma/docs/core/huggingface_text_finetune_qlora"><img src="https://ai.google.dev/static/site-assets/images/docs/notebook-site-button.png" height="32" width="32" />View on ai.google.dev</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/google-gemma/cookbook/blob/main/docs/core/huggingface_text_finetune_qlora.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/google-gemma/cookbook/blob/main/docs/core/huggingface_text_finetune_qlora.ipynb"><img src="https://www.kaggle.com/static/images/logos/kaggle-logo-transparent-300.png" height="32" width="70"/>Run in Kaggle</a>
  </td>
  <td>
    <a target="_blank" href="https://console.cloud.google.com/vertex-ai/colab/import/https%3A%2F%2Fraw.githubusercontent.com%2Fgoogle-gemma%2Fcookbook%2Fmain%2Fdocs%2Fcore%2Fhuggingface_text_finetune_qlora.ipynb"><img src="https://ai.google.dev/images/cloud-icon.svg" width="40" />Open in Vertex AI</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/google-gemma/cookbook/blob/main/docs/core/huggingface_text_finetune_qlora.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

## What is Quantized Low-Rank Adaptation (QLoRA)

This guide demonstrates the use of [Quantized Low-Rank Adaptation (QLoRA)](https://arxiv.org/abs/2305.14314), which emerged as a popular method to efficiently fine-tune LLMs as it reduces computational resource requirements while maintaining high performance. In QloRA, the pretrained model is quantized to 4-bit and the weights are frozen. Then trainable adapter layers (LoRA) are attached and only the adapter layers are trained. Afterwards, the adapter weights can be merged with the base model or kept as a separate adapter.

## Setup development environment

The first step is to install Hugging Face Libraries, including TRL, and datasets to fine-tune open model, including different RLHF and alignment techniques.
"""

"""_Note: If you are using a GPU with Ampere architecture (such as NVIDIA L4) or newer, you can use Flash attention. Flash Attention is a method that significantly speeds computations up and reduces memory usage from quadratic to linear in sequence length, leading to acelerating training up to 3x. Learn more at [FlashAttention](https://github.com/Dao-AILab/flash-attention/tree/main)._

You need a valid Hugging Face Token to publish your model. If you are running inside a Google Colab, you can securely use your Hugging Face Token using the Colab secrets otherwise you can set the token as directly in the `login` method. Make sure your token has write access too, as you push your model to the Hub during training.
"""

from pathlib import Path
from typing import Any
from datetime import datetime
import json
from datasets import Dataset, DatasetDict

import torch
import wandb
from transformers import AutoProcessor, AutoModelForMultimodalLM, BitsAndBytesConfig
from peft import prepare_model_for_kbit_training, LoraConfig, PeftModel
from trl import SFTConfig, SFTTrainer

# Login into Hugging Face Hub
from huggingface_hub import login
import os
from dotenv import load_dotenv

# Pre-built SFT datasets (see spider_sft_data_prep.ipynb). Each line is one JSON
# record carrying a chat-formatted prompt/completion pair plus Spider metadata.
DATA_DIR = Path(__file__).parent / "spider_data_jsonl"
TRAIN_JSONL = DATA_DIR / "spider_train_sft.jsonl"
DEV_JSONL = DATA_DIR / "spider_dev_sft.jsonl"

# Run identity, shared between the Hub repo name and the W&B run
PROJECT_NAME = "gemma-text-to-sql"

# Hugging Face model id
MODEL_ID = "google/gemma-4-E2B" # @param ["google/gemma-4-E2B","google/gemma-4-E4B","google/gemma-4-12B","google/gemma-4-31B","google/gemma-4-26B-A4B"] {"allow-input":true}

# Quick local smoke-test switch: trims the dataset and lightens hyperparameters so the
# whole pipeline can be exercised in a few minutes on a single 16GB GPU. Set to False for a full training run.
LITE_MODE = False

LITE_TRAIN_SAMPLES = 500
LITE_EVAL_SAMPLES = 125
LITE_MAX_LENGTH = 512
LITE_NUM_EPOCHS = 1
LITE_LOGGING_STEPS = 1
LITE_CHECKPOINT_EVAL_STEPS = 100

FULL_MAX_LENGTH = 1024
FULL_NUM_EPOCHS = 3
FULL_LOGGING_STEPS = 10
FULL_CHECKPOINT_EVAL_STEPS = 500

"""## Load the fine-tuning dataset

The prompts are pre-built by `spider_sft_data_prep.ipynb`, which writes one JSON
record per line into `spider_data_jsonl/`. Each record is already chat-formatted,
so this script no longer renders prompt templates or reads schemas out of the
SQLite files — it only normalises the records into the prompt/completion layout
the collator expects:

```
{
  "prompt": [{"role": "system", ...}, {"role": "user", ...}],
  "completion": [{"role": "assistant", "content": "SELECT ..."}],
  "db_id": "department_management",
  "gold_sql": "SELECT ..."
}
```

Records written in the single-list `messages` layout are accepted too: the
trailing assistant turn is split off as the completion.
"""

# Columns carried alongside the conversation, purely for debugging/eval joins.
METADATA_COLUMNS = ("db_id", "gold_sql")


def split_messages(messages: list[dict[str, str]]) -> tuple[list, list]:
    """Split a flat `messages` list into (prompt, completion) at the final
    assistant turn, so `messages`-style records train identically to
    prompt/completion ones."""
    for idx in range(len(messages) - 1, -1, -1):
        if messages[idx]["role"] == "assistant":
            return messages[:idx], messages[idx:]
    raise ValueError("record has no assistant turn to train on")


def normalize_record(record: dict[str, Any]) -> dict[str, Any]:
    """Reduce one raw JSONL record to the fields the trainer uses.

    Anything else in the record (e.g. the pre-rendered `text` field, or the raw
    `question`) is dropped here, before it ever reaches Arrow's schema
    inference."""
    if "prompt" in record and "completion" in record:
        prompt, completion = record["prompt"], record["completion"]
    elif "messages" in record:
        prompt, completion = split_messages(record["messages"])
    else:
        raise ValueError(
            "record must contain either 'prompt' and 'completion' or 'messages'; "
            f"got keys {sorted(record)}"
        )

    normalized = {"prompt": prompt, "completion": completion}
    for column in METADATA_COLUMNS:
        normalized[column] = record.get(column, "")
    return normalized


def load_sft_jsonl(path: Path) -> list[dict[str, Any]]:
    """Load a JSONL SFT split into normalised prompt/completion records."""
    with path.open(encoding="utf-8") as f:
        return [normalize_record(json.loads(line)) for line in f if line.strip()]


def conversation(example: dict[str, Any]) -> list[dict[str, str]]:
    """The full conversation (prompt turns followed by the assistant answer)."""
    return example["prompt"] + example["completion"]


def build_token_length_fn(processor):
    """Return a function that measures the chat-templated token length of an
    example, for filtering out examples that won't fit max_length."""
    def token_length(example: dict[str, Any]) -> int:
        full_text = processor.apply_chat_template(
            conversation(example), add_generation_prompt=False, tokenize=False
        ).strip()
        return len(processor(text=[full_text])["input_ids"][0])
    return token_length


def build_collate_fn(processor, max_length: int):
    """Return a data collator bound to the given processor and max_length.

    Because the dataset keeps the prompt and the completion apart, the loss mask
    is derived from the exact tokenised length of the chat-templated prompt
    instead of scanning for the assistant header — the prompt rendered with
    `add_generation_prompt=True` is by construction a prefix of the full
    conversation."""
    def collate_fn(examples):
        texts = []
        prompt_texts = []

        for example in examples:
            full_text = processor.apply_chat_template(
                conversation(example), add_generation_prompt=False, tokenize=False
            )
            texts.append(full_text.strip())
            # No .strip() here: the generation prompt's trailing newline is part
            # of the prefix that must be masked out.
            prompt_texts.append(
                processor.apply_chat_template(
                    example["prompt"], add_generation_prompt=True, tokenize=False
                )
            )

        # Tokenize the texts and process the audios
        batch = processor(
            text=texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length,
        )

        # Tokenized prompts, unpadded, purely to measure the prefix to mask
        prompt_ids = processor(text=prompt_texts)["input_ids"]

        # The labels are the input_ids, and we mask the padding tokens and audio tokens in the loss computation
        labels = batch["input_ids"].clone()

        for i in range(labels.size(0)):
            row_tokens = batch["input_ids"][i].tolist()
            attention_mask = batch["attention_mask"][i].tolist()

            # First non-padding position, so the mask is correct whether the
            # processor pads on the left or on the right
            row_start = attention_mask.index(1)
            row_end = row_start + sum(attention_mask)
            prompt_end = min(row_start + len(prompt_ids[i]), row_end)

            if row_tokens[row_start:prompt_end] != prompt_ids[i][: prompt_end - row_start]:
                print("WARNING: prompt tokens are not a prefix of the conversation; "
                      "masking the whole row to avoid training on prompt text.")
                prompt_end = row_end

            if prompt_end >= row_end:
                print("WARNING: maybe the sample is too long, try to increase `token_limit` value.")

            # Keep loss on the assistant answer only
            labels[i, :prompt_end] = -100

        # Mask tokens for not being used in the loss computation
        labels[labels == processor.tokenizer.pad_token_id] = -100

        batch["labels"] = labels
        return batch
    return collate_fn


def main() -> None:
    print(f"LITE_MODE is {'ON' if LITE_MODE else 'OFF'}")

    # Load environment variables from .env file
    load_dotenv()

    hf_token = os.environ["HF_TOKEN"]
    login(hf_token, add_to_git_credential=True)

    run_name = f"{datetime.now():%Y-%m-%d_%H.%M.%S}-finetune-QLORA" + ("-lite" if LITE_MODE else "")
    project_run_name = f"{PROJECT_NAME}-{run_name}"

    # Log in to Weights & Biases
    wandb.login(key=os.environ["WANDB_API_KEY"])

    # Configure Weights & Biases to record against our project
    os.environ["WANDB_PROJECT"] = PROJECT_NAME
    os.environ["WANDB_LOG_MODEL"] = "false"
    os.environ["WANDB_WATCH"] = "false"

    wandb.init(project=PROJECT_NAME, name=run_name)

    # Load the dataset
    dataset = DatasetDict({
        "train": Dataset.from_list(load_sft_jsonl(TRAIN_JSONL)),
        "validation": Dataset.from_list(load_sft_jsonl(DEV_JSONL)),
    })
    print(f"Loaded {len(dataset['train'])} train / {len(dataset['validation'])} validation examples")

    # Print the first formatted conversation
    for message in conversation(dataset["train"][0]):
        print(message)

    """## Fine-tune Gemma using TRL and the SFTTrainer

    The following code loads the Gemma model and tokenizer from Hugging Face and initializes the quantization configuration.
    """

    # Check if GPU supports bfloat16
    if torch.cuda.is_bf16_supported():
        torch_dtype = torch.bfloat16
    else:
        torch_dtype = torch.float16

    # Define model init arguments
    model_kwargs = dict(
        dtype=torch_dtype, # What torch dtype to use
        device_map="auto", # Let torch decide how to load the model
    )

    # BitsAndBytesConfig: Enables 4-bit quantization to reduce model size/memory usage
    model_kwargs["quantization_config"] = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type='nf4',
        bnb_4bit_compute_dtype=torch_dtype,
        bnb_4bit_quant_storage=torch_dtype,
    )

    # Load model and processor
    model = AutoModelForMultimodalLM.from_pretrained(MODEL_ID, **model_kwargs)
    processor = AutoProcessor.from_pretrained("google/gemma-4-E2B-it") # Load the Instruction Processor to use the official Gemma template

    # NOTE: You should call the prepare_model_for_kbit_training() function to preprocess the quantized model for training.
    # On T4, we are skipping this step purely due to VRAM limitation and for a quick demonstration.
    if (torch.cuda.get_device_properties(0).total_memory/1024**3) > 16:
        model = prepare_model_for_kbit_training(model)

    """The `SFTTrainer` supports a built-in integration with `peft`, which makes it straightforward to efficiently tune LLMs using QLoRA. You only need to create a `LoraConfig` and provide it to the trainer."""

    peft_config = LoraConfig(
        lora_alpha=16,
        lora_dropout=0.05,
        r=16,
        bias="none",
        # no target_modules — PEFT's Gemma 4 defaults scope to the LM layers
        task_type="CAUSAL_LM",
        modules_to_save=["lm_head", "embed_tokens"], # make sure to save the lm_head and embed_tokens as you train the special tokens
        ensure_weight_tying=True,
    )

    """Before you can start your training, you need to define the hyperparameter you want to use in a `SFTConfig` instance."""

    args = SFTConfig(
        output_dir=project_run_name,            # directory to save and repository id
        max_length=LITE_MAX_LENGTH if LITE_MODE else FULL_MAX_LENGTH,       # max length for model and packing of the dataset
        num_train_epochs=LITE_NUM_EPOCHS if LITE_MODE else FULL_NUM_EPOCHS, # number of training epochs
        per_device_train_batch_size=1,          # batch size per device during training
        per_device_eval_batch_size=1,           # batch size per device during evaluation
        optim="adamw_torch_fused",              # use fused adamw optimizer
        logging_steps=LITE_LOGGING_STEPS if LITE_MODE else FULL_LOGGING_STEPS, # log every N steps
        save_strategy="no" if LITE_MODE else "epoch", # skip intermediate checkpoints in lite mode
        eval_strategy="steps",                  # evaluate checkpoint every eval_steps steps
        eval_steps=LITE_CHECKPOINT_EVAL_STEPS if LITE_MODE else FULL_CHECKPOINT_EVAL_STEPS,
        learning_rate=5e-5,                     # learning rate
        fp16=True if torch_dtype == torch.float16 else False,  # use float16 precision
        bf16=True if torch_dtype == torch.bfloat16 else False, # use bfloat16 precision
        lr_scheduler_type="constant",           # use constant learning rate scheduler
        push_to_hub=not LITE_MODE,              # don't push smoke-test runs to the hub
        report_to=["wandb", "tensorboard"],     # report metrics to W&B and tensorboard
        run_name=run_name,                      # W&B run name
        dataset_kwargs={"skip_prepare_dataset": True}, # important for collator
        remove_unused_columns = False,                 # important for collator
    )

    """Now that the DB schema is embedded in each prompt, some examples (schema-heavy DBs
    like baseball_1 or soccer_1) no longer fit in `max_length` tokens alongside their SQL
    answer. Rather than silently truncating those into the collator's fallback path (which
    would compute loss on truncated prompt text instead of the SQL target), drop them from
    the dataset up front."""

    token_length = build_token_length_fn(processor)

    lite_split_caps = {"train": LITE_TRAIN_SAMPLES, "validation": LITE_EVAL_SAMPLES}

    for split in dataset:
        before = len(dataset[split])
        dataset[split] = dataset[split].filter(
            lambda example: token_length(example) <= args.max_length
        )
        dropped = before - len(dataset[split])
        print(f"{split}: dropped {dropped}/{before} examples exceeding max_length={args.max_length} tokens")

        if LITE_MODE:
            cap = lite_split_caps[split]
            dataset[split] = dataset[split].select(range(min(cap, len(dataset[split]))))
            print(f"LITE_MODE: trimmed {split} to {len(dataset[split])} examples (post-filter)")

    collate_fn = build_collate_fn(processor, args.max_length)

    """You now have every building block you need to create your `SFTTrainer` to start the training of your model."""

    # Create Trainer object
    trainer = SFTTrainer(
        model=model,
        args=args,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
        peft_config=peft_config,
        processing_class=processor,
        data_collator=collate_fn,
    )

    """Start training by calling the `train()` method."""

    # Start training, the model will be automatically saved to the Hub and the output directory
    trainer.train()

    # Save the final model again to the Hugging Face Hub
    trainer.save_model()

    # Close out the W&B run so the learning curves are marked finished
    wandb.finish()

    """Before you can test your model, make sure to free the memory."""

    # free the memory again
    del model
    del trainer
    torch.cuda.empty_cache()

    """When using QLoRA, you only train adapters and not the full model. This means when saving the model during training you only save the adapter weights and not the full model. If you want to save the full model, which makes it easier to use with serving stacks like vLLM or TGI, you can merge the adapter weights into the model weights using the `merge_and_unload` method and then save the model with the `save_pretrained` method. This saves a default model, which can be used for inference.

    Note: It requires more than 30GB of CPU Memory when you want to merge the adapter into the model. You can skip this and continue with Test Model Inference.
    """

    # Load Model base model
    model = AutoModelForMultimodalLM.from_pretrained(MODEL_ID, low_cpu_mem_usage=True)

    # Merge LoRA and base model and save
    peft_model = PeftModel.from_pretrained(model, args.output_dir)
    merged_model = peft_model.merge_and_unload()
    merged_model.save_pretrained("text2sql_qlora", safe_serialization=True, max_shard_size="2GB")

    processor = AutoProcessor.from_pretrained("google/gemma-4-E2B-it")
    processor.save_pretrained("text2sql_qlora")


if __name__ == "__main__":
    main()
