# -*- coding: utf-8 -*-
"""huggingface_text_finetune_qlora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/google-gemma/cookbook/blob/main/docs/core/huggingface_text_finetune_qlora.ipynb

##### Copyright 2025 Google LLC.
"""

#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from pathlib import Path
from typing import Any
from datetime import datetime
import json
from datasets import Dataset, DatasetDict

import torch
import wandb
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import prepare_model_for_kbit_training, LoraConfig, PeftModel
from trl import SFTConfig, SFTTrainer

from spider_prompts import CHAT_TEMPLATE_KWARGS, configure_tokenizer

# Login into Hugging Face Hub
from huggingface_hub import login
import os
from dotenv import load_dotenv

# Pre-built SFT datasets (see spider_sft_data_prep.ipynb). Each line is one JSON
# record carrying a chat-formatted prompt/completion pair plus Spider metadata.
DATA_DIR = Path(__file__).parent / "spider_data_jsonl"
TRAIN_JSONL = DATA_DIR / "spider_train_sft.jsonl"
DEV_JSONL = DATA_DIR / "spider_dev_sft.jsonl"

# Everything the script writes locally lives under OUTPUT_DIR: one sub-directory
# per training run (adapter, checkpoints, TensorBoard logs, merged model), and the
# W&B run files.
OUTPUT_DIR = Path(__file__).parent / "out"
# Each run merges its adapter into the base model under <run dir>/MERGED_SUBDIR.
MERGED_SUBDIR = "merged"
# Stable symlink to the merged model of the most recent full (non-lite) run. The
# test and evaluate scripts load from here by default.
LATEST_MODEL_LINK = OUTPUT_DIR / "text2sql_qlora_llama"

# Run identity, shared between the Hub repo name and the W&B run
PROJECT_NAME = "llama-text-to-sql"

# Hugging Face model id. The Instruct model provides both the weights and the tokenizer /
# official chat template (the Llama 3 base models have untrained embeddings for the chat
# special tokens, so the Instruct variants are the ones to fine-tune with a chat template).
# Other models to try (all gated: accept the license on the model page and use an HF_TOKEN
# with access). The VRAM figures are rough, for 4-bit QLoRA with a small per-device batch
# (lower BATCH_SIZE and raise GRADIENT_ACCUMULATION_STEPS to fit); the merge step at the end
# also needs about the bf16 model size in CPU RAM.
#   "meta-llama/Llama-3.2-1B-Instruct"   ~1B  smaller/faster, fits a 16GB GPU easily
#   "meta-llama/Llama-3.2-3B-Instruct"   ~3B  fits a 16GB GPU (current choice)
#   "meta-llama/Llama-3.1-8B-Instruct"   ~8B  ~24GB GPU, ~16GB CPU RAM to merge
#   "meta-llama/Llama-3.3-70B-Instruct"  ~70B ~80GB GPU (or several smaller ones), ~140GB CPU RAM to merge
MODEL_ID = "meta-llama/Llama-3.2-3B-Instruct"

# Quick local smoke-test switch: trims the dataset and lightens hyperparameters so the
# whole pipeline can be exercised in a few minutes on a single 16GB GPU. Set to False for a full training run.
LITE_MODE = False

LITE_TRAIN_SAMPLES = 1000
LITE_EVAL_SAMPLES = 250

# Logging / evaluation cadence. Steps are optimizer steps, i.e. one per
# BATCH_SIZE x GRADIENT_ACCUMULATION_STEPS samples.
LOGGING_STEPS = 1 if LITE_MODE else 10
CHECKPOINT_EVAL_STEPS = 4 if LITE_MODE else 30  # lite: ~16 optimizer steps in total, so evaluate about 4 times

# Hyper-parameters - overall

EPOCHS = 1 if LITE_MODE else 3
EFFECTIVE_BATCH_SIZE = 32 if LITE_MODE else 256  # samples per optimizer step
# Per-device batch, sized for the GPU: lite mode for the 16GB local GPU, full runs for the 24GB
# HPC GPU. Gradient accumulation makes up the rest of the effective batch, so if there is memory
# to spare, raise BATCH_SIZE and the accumulation follows.
BATCH_SIZE = 4 if LITE_MODE else 8
GRADIENT_ACCUMULATION_STEPS = EFFECTIVE_BATCH_SIZE // BATCH_SIZE
MAX_SEQUENCE_LENGTH = 512  # examples longer than this many tokens are dropped from the dataset

# Hyper-parameters - QLoRA

QUANT_4_BIT = True  # False loads the model unquantized (plain LoRA)
LORA_R = 32 if LITE_MODE else 256
LORA_ALPHA = LORA_R * 2
ATTENTION_LAYERS = ["q_proj", "v_proj", "k_proj", "o_proj"]
MLP_LAYERS = ["gate_proj", "up_proj", "down_proj"]
TARGET_MODULES = ATTENTION_LAYERS if LITE_MODE else ATTENTION_LAYERS + MLP_LAYERS
LORA_DROPOUT = 0.1

# Hyper-parameters - training

LEARNING_RATE = 1e-4
WARMUP_RATIO = 0.01  # linear LR warmup, as a fraction of total optimizer steps, followed by the scheduler below
LR_SCHEDULER_TYPE = 'cosine'
WEIGHT_DECAY = 0.001
OPTIMIZER = "paged_adamw_32bit"
SAVE_STRATEGY = "no" if LITE_MODE else "best"

"""## Load the fine-tuning dataset

The prompts are pre-built by `spider_sft_data_prep.ipynb`, which writes one JSON
record per line into `spider_data_jsonl/`. Each record is already chat-formatted,
so this script no longer renders prompt templates or reads schemas out of the
SQLite files — it only normalises the records into the prompt/completion layout
the collator expects:

```
{
  "prompt": [{"role": "system", ...}, {"role": "user", ...}],
  "completion": [{"role": "assistant", "content": "SELECT ..."}],
  "db_id": "department_management",
  "gold_sql": "SELECT ..."
}
```

Records written in the single-list `messages` layout are accepted too: the
trailing assistant turn is split off as the completion.
"""

# Columns carried alongside the conversation, purely for debugging/eval joins.
METADATA_COLUMNS = ("db_id", "gold_sql")


def split_messages(messages: list[dict[str, str]]) -> tuple[list, list]:
    """Split a flat `messages` list into (prompt, completion) at the final
    assistant turn, so `messages`-style records train identically to
    prompt/completion ones."""
    for idx in range(len(messages) - 1, -1, -1):
        if messages[idx]["role"] == "assistant":
            return messages[:idx], messages[idx:]
    raise ValueError("record has no assistant turn to train on")


def normalize_record(record: dict[str, Any]) -> dict[str, Any]:
    """Reduce one raw JSONL record to the fields the trainer uses.

    Anything else in the record (e.g. the pre-rendered `text` field, or the raw
    `question`) is dropped here, before it ever reaches Arrow's schema
    inference."""
    if "prompt" in record and "completion" in record:
        prompt, completion = record["prompt"], record["completion"]
    elif "messages" in record:
        prompt, completion = split_messages(record["messages"])
    else:
        raise ValueError(
            "record must contain either 'prompt' and 'completion' or 'messages'; "
            f"got keys {sorted(record)}"
        )

    normalized = {"prompt": prompt, "completion": completion}
    for column in METADATA_COLUMNS:
        normalized[column] = record.get(column, "")
    return normalized


def load_sft_jsonl(path: Path) -> list[dict[str, Any]]:
    """Load a JSONL SFT split into normalised prompt/completion records."""
    with path.open(encoding="utf-8") as f:
        return [normalize_record(json.loads(line)) for line in f if line.strip()]


def conversation(example: dict[str, Any]) -> list[dict[str, str]]:
    """The full conversation (prompt turns followed by the assistant answer)."""
    return example["prompt"] + example["completion"]


def build_token_length_fn(tokenizer):
    """Return a function that measures the chat-templated token length of an
    example, for filtering out examples that won't fit max_length."""
    def token_length(example: dict[str, Any]) -> int:
        full_text = tokenizer.apply_chat_template(
            conversation(example), add_generation_prompt=False, tokenize=False, **CHAT_TEMPLATE_KWARGS
        ).strip()
        # add_special_tokens=False: the chat template already writes <|begin_of_text|>
        return len(tokenizer(text=full_text, add_special_tokens=False)["input_ids"])
    return token_length


def build_collate_fn(tokenizer, max_length: int):
    """Return a data collator bound to the given tokenizer and max_length.

    Because the dataset keeps the prompt and the completion apart, the loss mask
    is derived from the exact tokenised length of the chat-templated prompt
    instead of scanning for the assistant header — the prompt rendered with
    `add_generation_prompt=True` is by construction a prefix of the full
    conversation."""
    def collate_fn(examples):
        texts = []
        prompt_texts = []

        for example in examples:
            full_text = tokenizer.apply_chat_template(
                conversation(example), add_generation_prompt=False, tokenize=False, **CHAT_TEMPLATE_KWARGS
            )
            texts.append(full_text.strip())
            # No .strip() here: the generation prompt's trailing newlines are part
            # of the prefix that must be masked out.
            prompt_texts.append(
                tokenizer.apply_chat_template(
                    example["prompt"], add_generation_prompt=True, tokenize=False, **CHAT_TEMPLATE_KWARGS
                )
            )

        # Tokenize the texts. add_special_tokens=False because the chat template
        # already writes <|begin_of_text|>; the tokenizer would add a second one.
        batch = tokenizer(
            text=texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length,
            add_special_tokens=False,
        )

        # Tokenized prompts, purely to measure the prefix to mask. Must be tokenized
        # exactly like the texts above (no padding, no extra special tokens) or the
        # prefix comparison below breaks.
        prompt_ids = tokenizer(text=prompt_texts, padding=False, add_special_tokens=False)["input_ids"]

        # The labels are the input_ids; the prompt and the padding are masked out of the loss
        labels = batch["input_ids"].clone()

        for i in range(labels.size(0)):
            row_tokens = batch["input_ids"][i].tolist()
            attention_mask = batch["attention_mask"][i].tolist()

            # First non-padding position, so the mask is correct whether the
            # tokenizer pads on the left or on the right
            row_start = attention_mask.index(1)
            row_end = row_start + sum(attention_mask)
            prompt_end = min(row_start + len(prompt_ids[i]), row_end)

            if row_tokens[row_start:prompt_end] != prompt_ids[i][: prompt_end - row_start]:
                print("WARNING: prompt tokens are not a prefix of the conversation; "
                      "masking the whole row to avoid training on prompt text.")
                prompt_end = row_end

            if prompt_end >= row_end:
                print("WARNING: maybe the sample is too long, try to increase `token_limit` value.")

            # Keep loss on the assistant answer only
            labels[i, :prompt_end] = -100

        # Mask padding. The pad token differs from <|eot_id|> (see configure_tokenizer),
        # so the end of the answer stays in the loss.
        labels[labels == tokenizer.pad_token_id] = -100

        batch["labels"] = labels
        return batch
    return collate_fn


def update_latest_link(link: Path, target: Path) -> None:
    """Atomically point `link` at `target`, using a relative symlink so the
    project directory can be moved.

    A real directory at `link` (e.g. a merged model saved before runs got their
    own merged dir) is never replaced: it may be the only copy of that model."""
    if link.exists() and not link.is_symlink():
        print(f"WARNING: {link} is a real directory, not a symlink; leaving it untouched. "
              f"Move or delete it to let it track the latest run (latest merge is at {target}).")
        return
    tmp_link = link.with_name(link.name + ".tmp")
    tmp_link.unlink(missing_ok=True)
    tmp_link.symlink_to(os.path.relpath(target, link.parent), target_is_directory=True)
    os.replace(tmp_link, link)
    print(f"{link} -> {target}")


def main() -> None:
    print(f"LITE_MODE is {'ON' if LITE_MODE else 'OFF'}")

    # Load environment variables from .env file
    load_dotenv()

    hf_token = os.environ["HF_TOKEN"]
    login(hf_token, add_to_git_credential=True)

    run_name = f"{datetime.now():%Y-%m-%d_%H.%M.%S}-finetune-QLORA" + ("-lite" if LITE_MODE else "")
    project_run_name = f"{PROJECT_NAME}-{run_name}"

    # Log in to Weights & Biases
    wandb.login(key=os.environ["WANDB_API_KEY"])

    # Configure Weights & Biases to record against our project
    os.environ["WANDB_PROJECT"] = PROJECT_NAME
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    os.environ["WANDB_DIR"] = str(OUTPUT_DIR)
    os.environ["WANDB_LOG_MODEL"] = "false"
    os.environ["WANDB_WATCH"] = "false"

    wandb.init(project=PROJECT_NAME, name=run_name)

    # Load the dataset
    dataset = DatasetDict({
        "train": Dataset.from_list(load_sft_jsonl(TRAIN_JSONL)),
        "validation": Dataset.from_list(load_sft_jsonl(DEV_JSONL)),
    })
    print(f"Loaded {len(dataset['train'])} train / {len(dataset['validation'])} validation examples")

    # Print the first formatted conversation
    for message in conversation(dataset["train"][0]):
        print(message)

    """## Fine-tune Llama using TRL and the SFTTrainer

    The following code loads the Llama model and tokenizer from Hugging Face and initializes the quantization configuration.
    """

    # Check if GPU supports bfloat16
    if torch.cuda.is_bf16_supported():
        torch_dtype = torch.bfloat16
    else:
        torch_dtype = torch.float16

    # Define model init arguments
    model_kwargs = dict(
        dtype=torch_dtype, # What torch dtype to use
        device_map="auto", # Let torch decide how to load the model
    )

    # BitsAndBytesConfig: Enables 4-bit quantization to reduce model size/memory usage
    if QUANT_4_BIT:
        quant_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type='nf4',
            bnb_4bit_compute_dtype=torch_dtype,
            bnb_4bit_quant_storage=torch_dtype,
        )
    else:
        quant_config = BitsAndBytesConfig(
            load_in_8bit=True,
            bnb_8bit_compute_dtype=torch_dtype,
        )

    model_kwargs["quantization_config"] = quant_config

    # Load model and tokenizer (the Instruct repo carries the official Llama chat template).
    # Right padding for training; the tokenizer is saved next to the merged model.
    model = AutoModelForCausalLM.from_pretrained(MODEL_ID, **model_kwargs)
    tokenizer = configure_tokenizer(AutoTokenizer.from_pretrained(MODEL_ID), padding_side="right")

    # NOTE: You should call the prepare_model_for_kbit_training() function to preprocess the quantized model for training.
    # On T4, we are skipping this step purely due to VRAM limitation and for a quick demonstration.
    if QUANT_4_BIT and (torch.cuda.get_device_properties(0).total_memory/1024**3) > 16:
        model = prepare_model_for_kbit_training(model)

    """The `SFTTrainer` supports a built-in integration with `peft`, which makes it straightforward to efficiently tune LLMs using QLoRA. You only need to create a `LoraConfig` and provide it to the trainer."""

    lora_config = LoraConfig(
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        r=LORA_R,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=TARGET_MODULES,
    )

    """Before you can start your training, you need to define the hyperparameter you want to use in a `SFTConfig` instance."""

    train_parameters = SFTConfig(
        output_dir=str(OUTPUT_DIR / project_run_name), # directory to save; its basename is the Hub repo name
        num_train_epochs=EPOCHS,                # number of training epochs
        per_device_train_batch_size=BATCH_SIZE, # batch size per device during training
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS, # effective batch = BATCH_SIZE x this
        per_device_eval_batch_size=1,           # batch size per device during evaluation
        optim=OPTIMIZER,                        # optimizer
        weight_decay=WEIGHT_DECAY,              # weight decay
        logging_steps=LOGGING_STEPS,            # log every N steps
        save_strategy=SAVE_STRATEGY,            # "best": save only when eval_loss improves; lite mode skips checkpoints
        eval_strategy="steps",                  # evaluate checkpoint every eval_steps steps
        eval_steps=CHECKPOINT_EVAL_STEPS,
        learning_rate=LEARNING_RATE,            # learning rate
        fp16=True if torch_dtype == torch.float16 else False,  # use float16 precision
        bf16=True if torch_dtype == torch.bfloat16 else False, # use bfloat16 precision
        max_grad_norm=0.3,
        max_steps=-1,
        warmup_steps=WARMUP_RATIO,              # a float < 1 is a fraction of total optimizer steps
        lr_scheduler_type=LR_SCHEDULER_TYPE,    # LR schedule after warmup
        push_to_hub=not LITE_MODE,              # don't push smoke-test runs to the hub
        report_to="wandb",                      # report metrics to W&B
        run_name=run_name,                      # W&B run name
        max_length=MAX_SEQUENCE_LENGTH,         # max length for model and packing of the dataset
        dataset_kwargs={"skip_prepare_dataset": True}, # important for collator
        remove_unused_columns = False,                 # important for collator
        load_best_model_at_end=not LITE_MODE,   # restore the lowest-eval-loss adapter before the final save/merge
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        save_total_limit=1,                     # each checkpoint is ~3GB; only the best one is kept
        # No assistant_only_loss / dataset_text_field: response-only loss is built by
        # build_collate_fn (skip_prepare_dataset bypasses TRL's own masking), and
        # assistant_only_loss=True makes SFTTrainer demand a `{% generation %}` chat
        # template, which stock chat templates (Llama 3's included) do not have.
    )

    """Now that the DB schema is embedded in each prompt, some examples (schema-heavy DBs
    like baseball_1 or soccer_1) no longer fit in `max_length` tokens alongside their SQL
    answer. Rather than silently truncating those into the collator's fallback path (which
    would compute loss on truncated prompt text instead of the SQL target), drop them from
    the dataset up front."""

    token_length = build_token_length_fn(tokenizer)

    lite_split_caps = {"train": LITE_TRAIN_SAMPLES, "validation": LITE_EVAL_SAMPLES}

    for split in dataset:
        before = len(dataset[split])
        dataset[split] = dataset[split].filter(
            lambda example: token_length(example) <= train_parameters.max_length
        )
        dropped = before - len(dataset[split])
        print(f"{split}: dropped {dropped}/{before} examples exceeding max_length={train_parameters.max_length} tokens")
        if not len(dataset[split]):
            # An empty validation split would otherwise only fail after the first epoch
            # (no eval_loss for best-model selection); an empty train split is just as fatal.
            raise ValueError(
                f"All {before} {split} examples exceed max_length={train_parameters.max_length} tokens. "
                "Increase MAX_SEQUENCE_LENGTH: every prompt carries the DB schema, so examples "
                "typically need a few hundred tokens."
            )

        if LITE_MODE:
            cap = lite_split_caps[split]
            dataset[split] = dataset[split].select(range(min(cap, len(dataset[split]))))
            print(f"LITE_MODE: trimmed {split} to {len(dataset[split])} examples (post-filter)")

    collate_fn = build_collate_fn(tokenizer, train_parameters.max_length)

    """You now have every building block you need to create your `SFTTrainer` to start the training of your model."""

    # Create Trainer object
    trainer = SFTTrainer(
        model=model,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
        peft_config=lora_config,
        args=train_parameters,
        processing_class=tokenizer,
        data_collator=collate_fn,
    )

    """Start training by calling the `train()` method."""

    # Start training, the model will be automatically saved to the Hub and the output directory
    trainer.train()

    # Save the final model again to the Hugging Face Hub
    trainer.save_model()

    # Close out the W&B run so the learning curves are marked finished
    wandb.finish()

    """Before you can test your model, make sure to free the memory."""

    # free the memory again
    del model
    del trainer
    torch.cuda.empty_cache()

    """When using QLoRA, you only train adapters and not the full model. This means when saving the model during training you only save the adapter weights and not the full model. If you want to save the full model, which makes it easier to use with serving stacks like vLLM or TGI, you can merge the adapter weights into the model weights using the `merge_and_unload` method and then save the model with the `save_pretrained` method. This saves a default model, which can be used for inference.

    Note: It requires more than 30GB of CPU Memory when you want to merge the adapter into the model. You can skip this and continue with Test Model Inference.
    """

    # Load Model base model
    model = AutoModelForCausalLM.from_pretrained(MODEL_ID, low_cpu_mem_usage=True)

    # Merge LoRA and base model and save next to the adapter it came from
    merged_model_dir = Path(train_parameters.output_dir) / MERGED_SUBDIR
    peft_model = PeftModel.from_pretrained(model, train_parameters.output_dir)
    merged_model = peft_model.merge_and_unload()
    merged_model.save_pretrained(merged_model_dir, safe_serialization=True, max_shard_size="2GB")

    # Reuse the tokenizer from training (SFTTrainer leaves it unchanged with this config)
    tokenizer.save_pretrained(merged_model_dir)
    print(f"Merged model saved to {merged_model_dir}")

    # Smoke-test (lite) runs keep their merged model but never become "latest",
    # so they can't shadow the model from the last full run.
    if not LITE_MODE:
        update_latest_link(LATEST_MODEL_LINK, merged_model_dir)


if __name__ == "__main__":
    main()
